# Generated by Django 3.1.2 on 2020-10-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0002_customimage_customrendition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='collage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='duplicate.collage'),
        ),
    ]
