# Generated by Django 3.1.2 on 2020-10-13 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0003_customimage_collage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collage',
            name='images',
        ),
        migrations.AddField(
            model_name='collage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='duplicate.customimage'),
        ),
    ]
