# Generated by Django 3.1.2 on 2020-10-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0005_customimage_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customrendition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customrendition',
            name='image',
        ),
        migrations.RemoveField(
            model_name='collage',
            name='main_image',
        ),
        migrations.DeleteModel(
            name='CustomImage',
        ),
        migrations.DeleteModel(
            name='CustomRendition',
        ),
    ]
