# Generated by Django 3.1.2 on 2020-10-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0008_auto_20201014_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='main_image',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current_collage', to='duplicate.customimage'),
        ),
    ]
