# Generated by Django 3.1.2 on 2020-10-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0009_collage_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='main_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_collage', to='duplicate.customimage'),
        ),
    ]
