# Generated by Django 3.1.2 on 2020-10-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0010_auto_20201014_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_collage', to='duplicate.customimage'),
        ),
    ]
