# Generated by Django 3.1.2 on 2020-10-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0012_auto_20201016_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collage',
            name='count_image',
        ),
    ]
