# Generated by Django 3.1.2 on 2020-10-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0013_remove_collage_count_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='main',
            field=models.BooleanField(null=True),
        ),
    ]
