# Generated by Django 3.1.2 on 2020-10-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0014_customimage_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='image_count',
            field=models.IntegerField(null=True),
        ),
    ]
