# Generated by Django 3.1.2 on 2020-10-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0016_auto_20201017_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collage',
            name='image_count',
        ),
    ]
