# Generated by Django 3.1.2 on 2020-10-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0017_remove_collage_image_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='image_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
